### PR TITLE
Add api keys for layers, documents and map

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
API Keys need to be generated with : `python manage.py backfill_api_keys`. You can find generated keys in `tastypie_apikey` table : 

```sql
SELECT people_profile.id, username, key 
FROM people_profile
LEFT JOIN tastypie_apikey ON (tastypie_apikey.user_id = people_profile.id)
```

Finally, add key and username in url :

Ex: http://127.0.0.1:8000/api/layers/?username=joe&api_key=xxxxxxxxxxxxxxxxxxxxxxxxxx
See : http://django-tastypie.readthedocs.io/en/v0.12.2/authentication.html#apikeyauthentication

**Comment by Vampouille** [comment]
Affected API URL :
* /api/base
* /api/featured
* /api/layers
* /api/maps
* /api/documents

Api URL **not** affected by API Keys :

* /api/keywords
* /api/thesaurus/keywords
* /api/regions
* /api/categories
* /api/groups
* /api/profiles
* /api/owners

**Comment by fvanderbiest** [comment]
This PR mixes branches ...

**Comment by Vampouille** [comment]
> This PR mixes branches ...

Fixed !

**Pull request merged**
